# Mouse support
set -g mouse on

# Shell and terminal settings
set-option -g default-shell /bin/bash
set -g default-terminal "screen-256color"

# Start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1

# Increase scrollback buffer
set -g history-limit 10000

# Status bar
set -g pane-border-status top
set -g status-left '#[fg=colour166][#S] '
set -g status-right '#[fg=colour166]%H:%M %d-%b-%y'

# Vi key bindings in copy mode
setw -g mode-keys vi
set-option -g set-clipboard on
bind-key -T copy-mode-vi y send-keys -X copy-pipe "xclip -selection clipboard"

# Reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded"
